# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cuisine', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('dno', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phn', models.IntegerField()),
                ('images', models.ImageField(max_length=10000, upload_to=b'')),
                ('gstin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('menupk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.menu')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurant'),
        ),
    ]
