# Generated by Django 2.0.5 on 2018-11-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='rest_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cuisine', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('gstin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dno', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phn', models.CharField(max_length=10)),
                ('images', models.ImageField(upload_to='media/')),
                ('cuisine', models.CharField(max_length=30)),
                ('menupk', models.ManyToManyField(to='index.rest_menu')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('Feedback', models.CharField(max_length=1000)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurants')),
                ('userpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurants'),
        ),
    ]
