# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_by_cuisine',
            name='email',
        ),
        migrations.RemoveField(
            model_name='search_by_cuisine',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rest',
        ),
        migrations.DeleteModel(
            name='search_by_cuisine',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
