# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phn',
            field=models.IntegerField(max_length=10),
        ),
    ]
