# Generated by Django 2.0.5 on 2018-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='images',
            field=models.ImageField(max_length=10000, upload_to=''),
        ),
    ]
