# Generated by Django 2.0.5 on 2018-11-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181102_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurants'),
        ),
    ]
