# Generated by Django 2.0.5 on 2018-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181101_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='images',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
