# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180902_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='rest_menu',
        ),
    ]
