# Generated by Django 2.0.5 on 2018-11-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181102_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='userpk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
