# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180902_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('Feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='search_by_cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dno', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phn', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='no', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurant'),
        ),
        migrations.AddField(
            model_name='search_by_cuisine',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='search_by_cuisine',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurant'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurant'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='userpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.owner'),
        ),
    ]
