# Generated by Django 2.0.5 on 2018-11-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181102_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='gstin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.restaurants'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='userpk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
