# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181023_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menupk',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menupk',
            field=models.ManyToManyField(to='index.rest_menu'),
        ),
    ]
